FROM gcc:11.2 as builder

# using bash shell
SHELL ["/bin/bash", "-c"]
COPY . /app
WORKDIR /app
RUN make && rm -r app

FROM alpine:3.15
# using bash shell
SHELL ["/bin/bash", "-c"]
COPY --from=builder /app/compiled-app /app/compiled-app
CMD ["./app/compiled-app"]