FROM gcc:11.2

# using bash shell
SHELL ["/bin/bash", "-c"]
ONBUILD COPY . /app/src
ONBUILD WORKDIR /app
ONBUILD RUN cd src && make && mv compiled-app ../ && cd .. && rm -r src
ONBUILD CMD ["./compiled-app"]