FROM whanos-c as builder

FROM alpine:3.15
# using bash shell
SHELL ["/bin/bash", "-c"]
# copy the compiled app from the builder image
COPY --from=builder /app/compiled-app /app/compiled-app
# run the app
CMD ["./app/compiled-app"]