apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: whanos
  name: system:serviceaccount:whanos:default
rules:
- apiGroups: [""]
  resources: ["services", "secrets"]
  verbs: ["get", "watch", "list"]