apiVersion: v1
kind: Service
metadata:
  name: whanos
  namespace: whanos
  labels:
    env: dev

spec:
  type: NodePort
  selector:
    app: whanos
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080