{{- if .Values.deployment.ports }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: whanos
spec:
  type: LoadBalancer
  ports:
    {{- range .Values.deployment.ports }}
    - targetPort: {{ . }}
      protocol: TCP
      port: {{ . }}
      name: {{ . | quote }}
    {{- end }}
  selector:
    app: {{ .Release.Name }}
{{- end }}